@startuml pert2 
left to right direction 

actor User as user 
package restoran {
    actor Servent as serv 
    actor Chief as chief 
}

package Restoran {
    usecase "Pesan menu" as u1
    usecase "Bayar pesanan" as u2
    usecase "Melaporkan pesanan" as u3
    usecase "Memasak pesanan" as u4 
}

user --> U1
user --> U2
serv --> U3
chief --> u4



@enduml